#image: python:latest
image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
  NUGET_PATH: 'C:\NuGet\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe'

stages:
  - test_dotNet
  - build
  - test
#  - deploy

#build_job:
#  stage: build
#  only:
#    - tags  # the build process will only be started by git tag commits
#  script:
#    - '& "$env:NUGET_PATH" restore'  # restore Nuget dependencies
#    - '& "$env:MSBUILD_PATH" /p:Configuration=Release'  # build the project


test_dotNet_job:
  stage: test_dotNet
  script:
    - dotnet -h

build_job:
  stage: build
  script:
    - dotnet restore ./BackEnd/BackEnd.sln
    - dotnet build --no-restore ./BackEnd/BackEnd.sln

test_job:
  stage: test
  script:
    - dotnet test --no-build --collect:"XPlat Code Coverage" ./BackEnd/BackEnd.sln
    - dotnet test --no-build --logger "console;verbosity=detailed" ./BackEnd/BackEnd.sln
    
    
