name: .NET

on:
  push:
    branches: [ github-ci ]
  pull_request:
    branches: [ github-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore BackEnd 
    - name: Build
      run: dotnet build BackEnd --no-restore
    - name: Test
      run: dotnet test BackEnd --no-build -v n
